//nextと
import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
//react
import * as React from "react";
//components
import Listlink from "./components/Listlink";
//chakraUi
import { ChakraProvider } from "@chakra-ui/react"

export default function Home() {
  return (
    <ChakraProvider>
      <Listlink />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <h1 className="title">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
      <footer className="footer">
          <span className="logo">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
      </footer>
      </ChakraProvider>
  )
}
